Vagrantfile

- Added new lxc node to contain "management" services
- Improved "services up" check at end of process

Improved Performance by Splitting out Management Services onto a New LXC Node

---

Vagrantfile

- Add natdnsproxy1 vm property to virtualbox setup
- Add ioapic, apic, x2apic, and biosapic to virtualbox setup
- Set nonrotational flag on all disks
- Set hostiocache to on for the SATA Controller in virtualbox

Performance Tweaks

---

Vagrantfile

- set version = 2.1.0
- add kubelet_extra_args and kube_proxy_extra_args to cfc_hosts variable
- add sanity check post lxc node startup to ensure ip assigned and docker installed
- add docker container cleanup to startup script to trim exited docker containers
- add run: "always" to ensure_services_up vagrant script so it will run even on restarts
- add 'metering' and 'monitoring' to `disabled_management_services` in `Vagrantfile`  
- services can be added via the App Catalog in the management console  
- adding additional services to disabled list to increase number of users who can run the base ICP server

Update to version 2.1.0

---

README.md
terraform/openstack/README.rst
terraform/openstack/bootstrap_icp_ce_master.sh
terraform/openstack/bootstrap_icp_ee_master.sh
terraform/openstack/bootstrap_icp_worker.sh
terraform/openstack/main.tf
terraform/openstack/outputs.tf
terraform/openstack/variables.tf

@tpouyer FYI - ready for merging

Add Terraform module to deploy ICP atop OpenStack

---

README.md
cluster/Dockerfile
cluster/config.yaml

Install GA to SL with ansible.

Update ansible install on SL for GA release

---

Cachefile
Vagrantfile

- Set docker log rotation on
- Set additional docker image management k8s options
- Remove MTU optimizations

Fix for base box changes to bento/ubuntu-16.04

---

Vagrantfile

- Add support for ICP version 2.1.0.1  
- Added shutdown/startup scripts to enable use of `vagrant halt` and `vagrant up` for system shutdown and restart

Add support for v2.1.0.1

---

README.md
docs/deploy-nfs-provisioner.md
extensions/nfs-class.yaml
extensions/nfs-deployment.yaml
extensions/nfs-test-claim.yaml

Provide instructions to set up container-based kubernetes out-of-tree nfs-provisioner.

add optional nfs provisioner

---

camQuick.sh

Print a simple usage statement to the user when the script is run without any input params.

added Usage Output when $# -eq 0

---

camQuick.sh

this latest rev works for vagrant and Fyre ICP "ICp-2.1.0.2-Single_Ubuntu-16.04"

added steps to install kubectl and nfs packages

---

camQuick.sh

cleaned up usage statement parameterized dockeruser dockeremail in the kubectl secrete create

usage update, parameterized dockeruser dockeremail

---

terraform/openstack/bootstrap_icp_master.sh
terraform/openstack/bootstrap_icp_worker.sh
terraform/openstack/main.tf
terraform/openstack/variables.tf

Added support for RHEL master/worker nodes.
Also added a small feature for providing a prefix for instance names when deploying to multi user clouds.

Support for RHEL

---

camQuick.sh

updated NFS mount settings lines 63-66

updated NFS mount settings in camQuick.sh

---

terraform/openstack/bootstrap_icp_master.sh
terraform/openstack/bootstrap_icp_worker.sh
terraform/openstack/main.tf
terraform/openstack/outputs.tf
terraform/openstack/variables.tf

2.1.0.2 works with VA turned on, also support for ICP docker package and printing of worker IPs.
Fixed up some bad indenting from my previous commit.

Added 2.1.0.2 support

---

terraform/openstack/bootstrap_icp_worker.sh
terraform/openstack/main.tf

Added the rendering for the worker script so the variables can be passed. 
@tpouyer Please merge if it looks good. Thanks!

Fixed variable not getting passed to the worker script

---

terraform/openstack/bootstrap_icp_master.sh
terraform/openstack/bootstrap_icp_worker.sh

Added support for SLES operating systems.

Changes to support SLES bootstrap

---

terraform/aws/scripts/bootstrap.sh

Added support for 3.1 of ICP
It needs tidying up but it will get things moving.

Added a change to allow for the 3.1 install of ICP.

---

terraform/openstack/bootstrap_icp_master.sh
terraform/openstack/install_mcm.sh
terraform/openstack/main.tf
terraform/openstack/variables.tf

With mcm_download_location we can set in the variables MCM installation will be automated on top of ICP.

Install mcm controller and klusterlet

---

Cachefile
Vagrantfile

Although the previous merge for bento/ubuntu 16.04 update has only recently been accepted, I was already testing the installation with the latest version (201812.27.0). 👍

Updated bento/ubuntu to latest version

---

docs/deploy-openstack-terraform.md
docs/deploy-powervc-terraform.md
terraform/modules/cam/scripts/cam_install.sh
terraform/modules/mcm/main.tf
terraform/modules/mcm/scripts/mcm_cleanup.sh
terraform/modules/mcm/scripts/mcm_install.sh
terraform/modules/mcm/scripts/mcm_load.sh
terraform/modules/mcm/scripts/mcm_load_cleanup.sh
terraform/modules/mcm/variables.tf
terraform/openstack/deploy.tf
terraform/openstack/instances.tf
terraform/openstack/outputs.tf
terraform/openstack/variables.tf
terraform/powervc/deploy.tf
terraform/powervc/instances.tf
terraform/powervc/outputs.tf
terraform/powervc/variables.tf

1. Added support for management, proxy, VA nodes
2. Option to pass ICP configuration map via input variable.
3. Allow only Klusterlet install for MCM.

Added new features to Openstack Terraform module
