IBM/deploy-ibm-cloud-private

- README.md
- Vagrantfile
- Changed default version to pull 2.1.0-beta-3
- Changed README.md to indicate 8GiB of RAM now required to run with latest beta-3
- Added logic to `Vagrantfile` to wait for kube-system pods to come up before finishing
to avoid reports of errors loging in due to auth pods not being fully started yet
- Added entry in README.md describing shellinabox (Web Terminal) and how to login using it.
> Update version to 2.1.0-beta-3

- README.md
- Vagrantfile
- Turned on multi-cpu support by setting the `--ioapic` VirtualBox management flag to "on"
- Upped the swap size from 4GiB to 8GiB and tuned the "swappiness" setting to 60
- Now pre-pulling the correct image for cloudantdb (it's not called icp-datastore)
> Turned On Multi-CPU VirtualBox Flag. Dramatically improves performance!

- README.md
Added link to the 5.1 download page, and a comment in the README as to why 5.1..28 is needed (5.2 is not yet supported by Vagrant)
This tripped me up following the instructions.
> Update download link for VirtualBox 5.1.28 with comment

- playbooks/prepare_sl_vms.yml
NFS can be used for storage in ICP.  this makes sure its available on the OS.
> add nfs-common package to ubuntu install

- terraform/ibmcloud/main.tf
There are a lot of changes coming to the icp deploy module. As there's a danger that these changes will break backwards compability we've created versioning via tags. 
This PR locks the recipe to a version of icp deploy module that is known to work.
> lock terraform icp deploy module version to 1.0.0

- docs/deploy-softlayer-terraform.md
- terraform/ibmcloud/main.tf
- terraform/ibmcloud/variables.tf
When using terraform in SL, it's possible to end up with instances spread across VLANS in a DC. Avoid this by providing option to specify vlan id for public and private.
Allow users to customize admin user password.
For both changes, no action results in default behavior matching current repository.
> add sl vlan and icp admin password specification

- README.md
The terraform/openstack directory no longer contains a README as
the information has been moved to the docs directory and is already
linked to at the beginning of the root README.  This patch removes
the outdated reference and the end of the root README.
> Remove outdated document reference

- docs/deploy-softlayer-terraform.md
The installation instructions were lacking details on how to get the Softlayer infrastructure details and how to generate and register the ssh keys.
> Enhanced install instructions for deploying ICP on Softlayer via Terraform

- terraform/openstack/bootstrap_icp_master.sh
- terraform/openstack/main.tf
- terraform/openstack/variables.tf
This PR adds a variable to allow specifying the disabled_management_services config.yaml option in the terraform variables. The current default is to disable "va", but can be overridden by the variable definition.
> Added support for the disabled_management_services:  configuration option.

- Vagrantfile
The host entry will be 127.0.1.1 and not 127.0.0.1, hence a wildcard is needed.
This is required as the host-entry is 127.0.1.1 when running vagrant up on my Mac for the current tree, using a wildcard fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/deploy-ibm-cloud-private/106)
> fix so that 127.0.1.1 is replaced too

- terraform/openstack/bootstrap_icp_master.sh
- terraform/openstack/bootstrap_icp_worker.sh
- terraform/openstack/main.tf
- terraform/openstack/outputs.tf
- terraform/openstack/variables.tf
Support for ICP 2.1.0.3 in the terraform/openstack module. 
Added logic to get proper icp docker image name
Added install of socat
> ICP 2.1.0.3 support for terraform

- Vagrantfile
The parameter for installing kibana (as shown in https://www.ibm.com/support/knowledgecenter/en/SSBS6K_2.1.0.3/installing/config_yaml.html) is not install_kibana but kibana_install.
This should fix issue #92
> Change parameter for kibana

- terraform/openstack/bootstrap_icp_master.sh
The code checks the following conditions:
1. ICP 2.1.0.2 and earlier versions have arch appended to to the docker image only for ppc64le
2. ICP 2.1.0.3 do not have any arch mentioned in the image names
3. ICP 3.1.0 and beyond require arch mentioned in the images for ppc64le and amd64 arch types for ee while ce doesn't.
> Fixes to ICP version check for 3.1.0 and earlier versions

- terraform/openstack/bootstrap_icp_master.sh
- terraform/openstack/icp_worker_scaler.sh
- terraform/openstack/main.tf
First time configuration:
1. Master will start to boot first and starts the install steps,
2. Workers will boot and prepare itself with IP now assigned.
3. Provisioner will inject files required for install steps (including the script for add/remove workers) in master node.
Add/Remove workers (by changing icp_num_workers):
1. Worker resource will be added or deleted by Terraform.
2. Local-exec Provisioner in worker resource will remote login to master from the terminal during create and destroy.
3. Add/Remove script is called with worker information which add/delete worker from the cluster.
Things to note with this procedure:
1. Remote call is made to master for each worker IP.
2. Console output of adding/removing a worker is shown in Terraform output.
3. Use of provsioners instead of …
> add remove workers

- Vagrantfile
grub update (during `apt-get upgrade`) was trying to go interactive during `vagrant up` because of the modified grub config from an earlier step. 
change upgrade command to set options to use old config, and not go interactive.
> Force confold etc for apt-get upgrade

- terraform/openstack/bootstrap_icp_worker.sh
- terraform/openstack/main.tf
Deployment on OpenStack fails because eth0 no longer present on newer distributions
> OpenStack deployment network interface name change

- playbooks/prepare_sl_vms.yml
Made this small change on the playbook to include `--network host` parameter on docker build command to avoid apk to hang when trying to fetch Alpine linux image, as described on [docker-alpine issue 307](https://github.com/gliderlabs/docker-alpine/issues/307#issuecomment-357238983).
> Added parameter on build to avoid apk to hang

- playbooks/prepare_sl_vms.yml
Added an additional step to confirm if resolvconf package is installed before trying to disable it to avoid the playbook to abort, as reported on issue [160](https://github.com/IBM/deploy-ibm-cloud-private/issues/160)
> Check if resolvconf exists before trying to disable it

- Cachefile
- Vagrantfile
Updated to use bento/ubuntu-16.04 v201808.24.0.
Still have to try with ubuntu-18.04, but if we stick 16.04, a new version of the VM image has been released.
> Updated to use bento/ubuntu-16.04 v201808.24.0

- terraform/openstack/bootstrap_icp_master.sh
- terraform/openstack/main.tf
- terraform/openstack/variables.tf
As IBM Power Systems support various processor SMT levels, we should allow the user to adjust the level if they'd like.
User should be able to specify separate SMT levels for the master node. The SMT level can be changed in the bootstrap scripts (early on, prior to any installation being performed) via:
ppc64_cpu --smt=X
...where X is the desired SMT level (it can be any of: on, off, 1, 2, 4, 8).
> Allow SMT levels to be set for the master node

- Vagrantfile
Fixes #193.
Missing openssl package caused this error.
> Fix x509 Error

- README.md
- docs/deploy-powervc-terraform.md
- terraform/modules/cam/main.tf
- terraform/modules/cam/scripts/cam_cleanup.sh
- terraform/modules/cam/scripts/cam_install.sh
- terraform/modules/cam/variables.tf
- terraform/modules/mcm/main.tf
- terraform/modules/mcm/scripts/mcm_cleanup.sh
- terraform/modules/mcm/scripts/mcm_install.sh
- terraform/modules/mcm/variables.tf
- terraform/powervc/deploy.tf
- terraform/powervc/instances.tf
- terraform/powervc/main.tf
- terraform/powervc/outputs.tf
- terraform/powervc/scripts/bootstrap_icp_master.sh
- terraform/powervc/scripts/bootstrap_icp_worker.sh
- terraform/powervc/variables.tf
This code template uses https://github.com/ibm-cloud-architecture/terraform-module-icp-deploy to install ICP. This way need not maintain changes for new ICP releases. Also, it will help to reduce the code and make the current module more extensible for future updates.
* Divide the Terraform code for creating Instances and deploying ICP.
* Instances - the bootstrap code required for setting SMT, docker & NTP.
* ICP deployment - Use module https://github.com/ibm-cloud-architecture/terraform-module-icp-deploy.
* Create and use Terraform module for MCM install and cleanup.
* Create and use Terraform module for CAM install and cleanup.
> New Terraform template for PowerVC

- docs/deploy-openstack-terraform.md
- docs/deploy-powervc-terraform.md
- terraform/modules/mcm/main.tf
- terraform/modules/mcm/scripts/mcm_load.sh
- terraform/modules/mcm/scripts/mcm_upgrade.sh
- terraform/modules/mcm/scripts/mcm_upgrade_cleanup.sh
- terraform/modules/mcm/variables.tf
- terraform/openstack/deploy.tf
- terraform/openstack/variables.tf
- terraform/powervc/deploy.tf
- terraform/powervc/variables.tf
ICP comes pre-installed with basic features of MCM. To enable the user to configure full MCM (Controller & Klusterlet) we need to upgrade the specific charts. Have also kept the code for the older version.
> icp 3.2.0 mcm installation
